---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PN.
--- DateTime: 2024/8/25 8:53
---

-- 参数列表
local voucherId = ARGV[1] --优惠券id
local userId = ARGV[2] --用户id
local orderId = ARGV[3] --订单id

--Redis对应key
local stockKey = "seckill:stock:" .. voucherId
local orderKey = "seckill:order:" .. voucherId

--脚本逻辑
if (tonumber(redis.call("get", stockKey)) <= 0) then
    --库存不足
    return 1
end
--判断用户是否下过单
if (redis.call("sismember", orderKey, userId) == 1) then
    --此用户已下过单
    return 2
end
--扣减库存
redis.call("incrby", stockKey, -1)
--下单，将userId存入当前优惠券的set集合
redis.call("sadd", orderKey, userId)
--发送消息到队列中， XADD stream.orders * k1 v1 k2 v2 ...
redis.call("xadd","stream.orders","*","userId",userId,"voucherId",voucherId,"id",orderId)
return 0